name: ember_vs_ice
description: A showcasing of simple collision detection in Flame
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flame: 1.0.0-releasecandidate.11
  dashbook: 0.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

fonts:
  - family: Inconsolata
    fonts:
      - asset: Inconsolata-Medium.ttf

flutter:
  uses-material-design: true

  assets:
    - assets/images/
